import type { Metadata } from "next";
import { Mona_Sans } from "next/font/google";
import Navigation from "@/components/Navigation";
import "./globals.css";
import Footer from "@/components/Footer";

const monaSans = Mona_Sans({
  variable: "--font-mona-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${monaSans.variable} ${monaSans.variable} antialiased `}
      >
        <Navigation />
        {children}
        <Footer />
      </body>
    </html>
  );
}
